[package]
name = "charts_webapp"
version = "0.1.0"
authors = ["Elliott Mahler <join.together@gmail.com>"]

[dependencies]
rocket = "*"
rocket_codegen = "*"
postgres = { version="0.13", features=["with-chrono"]}
chrono = "0.2"